name: BetonQuestPixelmonIntegration
version: 0.0.1
author: Rachamon
main: dev.rachamon.betonquestpixelmonintegration.BetonQuestPixelmonIntegration
depend: [ BetonQuest, EverNifeCore ]
softdepend: []
api-version: 1.13