name: RachamonCore
version: 0.0.1
author: Rachamon
main: dev.rachamon.rachamoncore.RachamonCore
depend: []
softdepend: [ BetonQuest, BattlePass ]
api-version: 1.13

commands:
    rachamoncore:
        description: RachamonCore Command
        usage: /<command> [args]
        aliases: [ rc ]
        default: true
    palettetokens:
        description: PaletteTokens Command
        usage: /<command> [args]
        aliases: [ pt ]
        default: true
    pixelmonbooster:
        description: PixelmonBooster Command
        usage: /<command> [args]
        aliases: [ pb ]
        default: true
    pixelmondropslogger:
        description: PixelmonDropsLogger Command
        usage: /<command> [args]
        aliases: [ pdl ]
        default: true